### ISSUE TITLE
Metadata type

### ISSUE THREAD

**Issue by shiraki-y** [gyro-n/gopay-java-sdk#79]
The type of metadata is `Map<String, String>` now, but it should be allowed not only `String` but others, such as below:
```
        "metadata": {
            "array": [
                "string",
                12.3,
                null
            ],
            "number": 10
       }
```

Because of this matter, the following error occurs if there is a data which can't be converted to `Map<String, String>` when it's dealt with.

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 4098 path $.items[5].metadata.

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
	at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at jp.gopay.sdk.builders.RetrofitRequestCaller.dispatch(RetrofitRequestCaller.java:77)
	at jp.gopay.sdk.builders.RetrofitRequestCaller.dispatch(RetrofitRequestCaller.java:62)
	at jp.gopay.sdk.builders.RetrofitRequestCaller.dispatch(RetrofitRequestCaller.java:19)
	at jp.gopay.adminSDK.charge.ChargeIT$CreateAndDeleteChargeTest.shouldCreateCharge(ChargeIT.java:163)
```

**Comment by shiraki-y** [comment]
Change the type of metadata to `JsonObject`

**Comment by shiraki-y** [comment]
#95 was merged
